# Generated by Django 4.2.14 on 2024-07-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_markdowncontent_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdowncontent",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
