# Generated by Django 4.2.14 on 2024-07-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0003_alter_markdowncontent_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdowncontent",
            name="intro",
            field=models.TextField(blank=True),
        ),
    ]
