# Generated by Django 4.2.14 on 2024-08-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_markdowncontent_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdowncontent',
            options={'ordering': ['id'], 'verbose_name_plural': 'Doc pages'},
        ),
    ]
