# Generated by Django 4.2.14 on 2024-08-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0005_alter_markdowncontent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markdowncontent",
            options={"ordering": ["id"], "verbose_name_plural": "markdown content"},
        ),
        migrations.AlterField(
            model_name="markdowncontent",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="markdowncontent",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
