# Generated by Django 4.2.14 on 2024-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0006_alter_markdowncontent_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarkdownContent",
            new_name="DocsContent",
        ),
        migrations.AlterModelOptions(
            name="docscontent",
            options={"ordering": ["id"], "verbose_name_plural": "docs content"},
        ),
    ]
