# Generated by Django 4.2.14 on 2024-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0007_rename_markdowncontent_docscontent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docscontent",
            options={"ordering": ["ordering"], "verbose_name_plural": "docs content"},
        ),
        migrations.AddField(
            model_name="docscontent",
            name="ordering",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="docscontent",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
