# Generated by Django 4.2.14 on 2024-08-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0008_alter_docscontent_options_docscontent_ordering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docscontent",
            name="last_editted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
