# Generated by Django 4.2.14 on 2024-08-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0009_docscontent_last_editted"),
    ]

    operations = [
        migrations.AddField(
            model_name="docscontent",
            name="parent_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="docs.docscontent",
            ),
        ),
    ]
