# Generated by Django 4.2.14 on 2024-08-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0010_docscontent_parent_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docscontent",
            name="parent_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="docs.docscontent",
            ),
        ),
    ]
