# Generated by Django 4.2.16 on 2024-10-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0012_alter_docscontent_parent_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docscontent",
            name="title",
            field=models.CharField(
                help_text="You can enter up to 100 characters",
                max_length=100,
                unique=True,
            ),
        ),
    ]
