# Generated by Django 4.2.14 on 2024-08-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_feeddata_remove_feed_feed_data_and_more"),
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeedArchive",
            new_name="Archive",
        ),
        migrations.AlterModelOptions(
            name="archive",
            options={
                "ordering": ["-datetime_archived"],
                "verbose_name_plural": "archives",
            },
        ),
    ]
