# Generated by Django 4.2.14 on 2024-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_rename_feedarchive_archive_alter_archive_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
