# Generated by Django 4.2.14 on 2024-07-26 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_feed_datafeed_frequency_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="geocoded_column",
        ),
        migrations.AddField(
            model_name="feed",
            name="geocoded_column",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, verbose_name="State Coordinate"
            ),
        ),
    ]
