# Generated by Django 4.2.14 on 2024-07-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_feed_geocoded_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='apikeyurl',
            field=models.URLField(null=True, verbose_name='API Key URL'),
        ),
    ]
