# Generated by Django 4.2.14 on 2024-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_feed_apikeyurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="edate",
            field=models.DateField(null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="sdate",
            field=models.DateField(verbose_name="Start Date"),
        ),
    ]
