# Generated by Django 4.2.14 on 2024-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_feed_edate_alter_feed_sdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="edate",
            field=models.DateTimeField(null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="sdate",
            field=models.DateTimeField(verbose_name="Start Date"),
        ),
    ]
