# Generated by Django 4.2.14 on 2024-07-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_feed_feed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.TextField(default=""),
        ),
    ]
