# Generated by Django 4.2.14 on 2024-08-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_apikey_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ["sdate"]},
        ),
    ]
