# Generated by Django 4.2.14 on 2024-08-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_alter_feed_edate_alter_feed_sdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("OK", "ok"),
                            ("ER", "error"),
                            ("OU", "outdated"),
                            ("ST", "stale"),
                            ("OF", "offline"),
                        ],
                        default="OK",
                        max_length=2,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("datetime_checked", models.DateTimeField(auto_now_add=True)),
                ("notif_sent", models.BooleanField(default=False)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.feed"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FeedError",
        ),
    ]
