# Generated by Django 4.2.14 on 2024-08-01 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_feedstatus_delete_feederror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='active',
            field=models.BooleanField(editable=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='apikeyurl',
            field=models.URLField(editable=False, null=True, verbose_name='API Key URL'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='datafeed_frequency_update',
            field=models.DurationField(editable=False, null=True, verbose_name='Datafeed Update Frequency'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='edate',
            field=models.DateField(editable=False, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_data',
            field=models.JSONField(default=dict, editable=False, verbose_name='Feed Data'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feedname',
            field=models.TextField(editable=False, primary_key=True, serialize=False, verbose_name='Feed Name'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='format',
            field=models.TextField(editable=False, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='geocoded_column',
            field=django.contrib.gis.db.models.fields.PointField(editable=False, null=True, srid=4326, verbose_name='State Coordinate'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='issuingorganization',
            field=models.TextField(editable=False, verbose_name='Issuing Organization'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='lastingestedtosandbox',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last Ingested To Sandbox (UTC)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='needapikey',
            field=models.BooleanField(editable=False, verbose_name='Need API Key'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='pipedtosandbox',
            field=models.BooleanField(editable=False, verbose_name='Piped to Sandbox'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='pipedtosocrata',
            field=models.BooleanField(editable=False, verbose_name='Piped to Socrata'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sdate',
            field=models.DateField(editable=False, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='socratadatasetid',
            field=models.TextField(blank=True, editable=False, verbose_name='Socrata Dataset ID'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='state',
            field=models.TextField(editable=False, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(editable=False, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='version',
            field=models.TextField(editable=False, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='feedstatus',
            name='error_message',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='feedstatus',
            name='feed',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.feed'),
        ),
        migrations.AlterField(
            model_name='feedstatus',
            name='status_type',
            field=models.CharField(choices=[('OK', 'ok'), ('ER', 'error'), ('OU', 'outdated'), ('ST', 'stale'), ('OF', 'offline')], default='OK', editable=False, max_length=2),
        ),
    ]
