# Generated by Django 4.2.14 on 2024-08-01 16:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_feed_active_alter_feed_apikeyurl_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"verbose_name_plural": "API keys"},
        ),
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ["sdate"], "verbose_name_plural": "feeds"},
        ),
        migrations.AlterModelOptions(
            name="feedstatus",
            options={"verbose_name_plural": "feed statuses"},
        ),
        migrations.RemoveField(
            model_name="feedstatus",
            name="error_message",
        ),
        migrations.AlterField(
            model_name="feed",
            name="active",
            field=models.BooleanField(verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="apikeyurl",
            field=models.URLField(null=True, verbose_name="API Key URL"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="datafeed_frequency_update",
            field=models.DurationField(
                null=True, verbose_name="Datafeed Update Frequency"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="edate",
            field=models.DateField(null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_data",
            field=models.JSONField(default=dict, verbose_name="Feed Data"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feedname",
            field=models.CharField(
                max_length=150,
                primary_key=True,
                serialize=False,
                verbose_name="Feed Name",
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="format",
            field=models.CharField(max_length=150, verbose_name="Format"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="geocoded_column",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, verbose_name="State Coordinate"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="issuingorganization",
            field=models.CharField(max_length=150, verbose_name="Issuing Organization"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="lastingestedtosandbox",
            field=models.DateTimeField(
                null=True, verbose_name="Last Ingested To Sandbox (UTC)"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="needapikey",
            field=models.BooleanField(default=False, verbose_name="Need API Key"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="pipedtosandbox",
            field=models.BooleanField(verbose_name="Piped to Sandbox"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="pipedtosocrata",
            field=models.BooleanField(verbose_name="Piped to Socrata"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="sdate",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="socratadatasetid",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Socrata Dataset ID"
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="state",
            field=models.CharField(max_length=150, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="feed",
            name="version",
            field=models.CharField(max_length=150, verbose_name="Version"),
        ),
        migrations.AlterField(
            model_name="feedstatus",
            name="feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.feed"
            ),
        ),
        migrations.AlterField(
            model_name="feedstatus",
            name="status_type",
            field=models.CharField(
                choices=[
                    ("OK", "ok"),
                    ("ER", "error"),
                    ("OU", "outdated"),
                    ("ST", "stale"),
                    ("OF", "offline"),
                ],
                default="OK",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="StaleError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Stale End Date")),
                (
                    "error_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.feedstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stale errors",
            },
        ),
        migrations.CreateModel(
            name="SchemaError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_error_type",
                    models.CharField(max_length=50, verbose_name="Schema Error Type"),
                ),
                (
                    "schema_error_field",
                    models.CharField(max_length=50, verbose_name="Schema Error Field"),
                ),
                (
                    "error_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.feedstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "schema errors",
            },
        ),
        migrations.CreateModel(
            name="OutdatedError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateTimeField(verbose_name="Stale Update Date")),
                (
                    "error_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.feedstatus",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "outdated errors",
            },
        ),
    ]
