# Generated by Django 4.2.14 on 2024-08-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_apikey_options_alter_feed_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-datetime_checked'], 'verbose_name_plural': 'feed statuses'},
        ),
    ]
