# Generated by Django 4.2.14 on 2024-08-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_outdatederror_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaerror',
            name='schema_error_field',
            field=models.CharField(max_length=150, verbose_name='Schema Error Field'),
        ),
        migrations.AlterField(
            model_name='schemaerror',
            name='schema_error_type',
            field=models.CharField(max_length=150, verbose_name='Schema Error Type'),
        ),
    ]
