# Generated by Django 4.2.14 on 2024-08-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_feed_is_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['state'], 'verbose_name_plural': 'feeds'},
        ),
    ]
