# Generated by Django 5.2 on 2025-05-07 19:59

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_feeddata_remove_feed_feed_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={
                "ordering": [
                    models.OrderBy(
                        django.db.models.functions.comparison.NullIf(
                            "state", models.Value("")
                        ),
                        nulls_last=True,
                    ),
                    "feedname",
                ],
                "verbose_name_plural": "feeds",
            },
        ),
    ]
